### ISSUE TITLE
New Business Rule Required

### ISSUE THREAD

**Issue by cmonsalvec** [joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA#3]
Dear developers, 

Based on the impact of the pandemic in the 2020 results, the board of the company has approved a new business rull beginning january 2021: If the customer is male, over 25 and younger than 45 then it is needed to subtract $100 from the base premium.

Therefore, we ask you to modify the premium calculation adding this new rule.

Best regards,

**Comment by joeaespi** [comment]
now I will proceed to analyze the problem raised

**Comment by joeaespi** [comment]
The requirement has been simulated and now it has been assigned to @Darjotri  who will analyze it thoroughly and I will correctly program your request @cmonsalvec

**Comment by Darjotri** [comment]
The impact analysis has been performed @cmonsalvec, please let me know any problem or request. @joeaespi 
[Impact Analysis.docx](https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/files/5833422/Impact.Analysis.docx)

**Comment by cmonsalvec** [comment]
Dear @Darjotri I do agree with the analysis, and with the resources and time required for this request. Please continue with its development.

**Comment by Darjotri** [comment]
The solution has been built and here is the fragment of code added. @cmonsalvec @joeaespi 
https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/blob/7265cec2b1e5ef608bca32357c4f36edf61e27df/ec.edu.espol.workshops.second/src/test/java/ec/edu/espol/workshops/second/CarInsurance.java#L28-L36

https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/blob/7265cec2b1e5ef608bca32357c4f36edf61e27df/ec.edu.espol.workshops.second/src/test/java/ec/edu/espol/workshops/second/CarInsurance.java#L42-L46

**Comment by Darjotri** [comment]
The solution has been built and here is the fragment of code added. @cmonsalvec 
https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/blob/7265cec2b1e5ef608bca32357c4f36edf61e27df/ec.edu.espol.workshops.second/src/test/java/ec/edu/espol/workshops/second/CarInsurance.java#L28-L36

https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/blob/7265cec2b1e5ef608bca32357c4f36edf61e27df/ec.edu.espol.workshops.second/src/test/java/ec/edu/espol/workshops/second/CarInsurance.java#L42-L46

**Comment by Darjotri** [comment]
Now, testing will be performed by @joeaespi who will do regression and unit testing of the solution.

**Comment by joeaespi** [comment]
@Darjotri  one of the tests failed to be executed, here I attach the test report, 
[FirstTest.docx](https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/files/5846895/FirstTest.docx)
please check this case

**Comment by Darjotri** [comment]
@joeaespi I solved the failure founded.
https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/blob/a6e25cc0a5c090d0af121eeed4626848e0b24a1e/ec.edu.espol.workshops.second/src/test/java/ec/edu/espol/workshops/second/CarInsurance.java#L24-L28

**Comment by joeaespi** [comment]
@cmonsalvec  I attached the document with the acceptance test plan
[Acceptance_Test.docx](https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/files/5847245/Acceptance_Test.docx)

**Comment by cmonsalvec** [comment]
Thnaks @joeaespi , I do agree with the acceptance testing plan

**Comment by joeaespi** [comment]
Dear @cmonsalvec  the solution has been completed and our programmer @Darjotri  will release the new software version.

**Comment by Darjotri** [comment]
Dear @cmonsalvec , to use the new software´s version you should download the file from the following link: https://github.com/joeaespi/ISII-WORKSHOPS-PEDIDOS-EN-LINEA/blob/Issues_Management/CarInsurance.jar , also you should have installed Java SE https://www.oracle.com/technetwork/es/java/javase/downloads/index.html to execute the project, finally use the next command 'java -jar CarInsurance.jar' and now you can use the new version of software. @joeaespi

**Comment by cmonsalvec** [comment]
Dear @Darjotri , thanks for your clear instructions. We will follow them to try to use the new version of the code in our organization

**Comment by joeaespi** [comment]
Dear @cmonsalvec , we will expect your response about the use of the solution and If all is ok, we will close the issue.

**Comment by cmonsalvec** [comment]
Dear @joeaespi ,

We have been using the new version of the product in our organization, and it seems everybody is happy with it. Thanks.

**Comment by joeaespi** [comment]
Dear @cmonsalvec  we are glad that you liked it.
thanks for your time.
